import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import katex from 'katex';
import * as V from './visuals.mjs';
import {zhNotes} from './speaker-notes-zh.mjs';
const out=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const p=s=>`<p class="lead">${s}</p>`,small=s=>`<p class="small">${s}</p>`;
const f=(s,n=1)=>`<div class="fragment" data-step="${n}">${s}</div>`;
const call=(s,w=false)=>`<div class="callout${w?' warm':''}">${s}</div>`;
const cols=(a,b,wide=false)=>`<div class="cols${wide?' wide':''}"><div>${a}</div><div>${b}</div></div>`;
const list=a=>`<ul class="bul">${a.map(s=>`<li>${s}</li>`).join('')}</ul>`;
const eq=(s,sm=false)=>`<div class="equation${sm?' sm':''}">${katex.renderToString(s,{displayMode:true,throwOnError:true})}</div>`;
const fig=(n,c,h=370)=>`<figure class="paperfig"><img src="assets/fig${String(n).padStart(2,'0')}.png" alt="${c}" style="max-height:${h}px"><figcaption>${c}</figcaption></figure>`;
const table=(heads,rows,compact=false)=>`<table class="tb${compact?' compact':''}"><thead><tr>${heads.map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr class="${String(r[0]).startsWith('SimToolReal')?'highlight':''}">${r.map(x=>`<td><span>${x}</span></td>`).join('')}</tr>`).join('')}</tbody></table>`;
const video=(n,c)=>`<div class="video-wrap"><img class="loop-gif" src="assets/videos/${n}.gif" alt="Looping GIF: ${c}" loading="lazy" decoding="async"><img class="video-poster" src="assets/videos/${n}.jpg" alt="Video still: ${c}"><div class="video-caption"><span>${c} · looping GIF · silent · 1× speed</span><a href="https://simtoolreal.github.io/">Original project video ↗</a></div></div>`;
const videoSlide=(name,c,cues)=>cols(video(name,c),`<div class="stack"><div class="eyebrow">What to watch</div>${cues.map(s=>`<p class="video-cue">${s}</p>`).join('')}</div>`,true);
const pair=(items)=>'<div class="video-pair">'+items.map(([name,title,cue])=>'<div class="media-item"><h3>'+title+'</h3>'+video(name,title)+'<p class="pair-cue">'+cue+'</p></div>').join('')+'</div>';
const slides=[];
const add=(section,title,body,note,source='Kedia et al. · SimToolReal · arXiv:2602.16863v2',cls='')=>slides.push({section,title,body,note,source,cls});
add('','SimToolReal',`<div class="cover-bar"></div><div class="cover-copy"><div class="eyebrow">Research seminar</div><h1>SimTool<span class="teal">Real</span></h1><div class="subtitle">An Object-Centric Policy for<br>Zero-Shot Dexterous Tool Manipulation</div><p class="cover-question">Can one reusable controller<br>turn tool motion into robot skill?</p><div class="authors">Kushal Kedia* · Tyler Ga Wei Lum*<br>Jeannette Bohg · C. Karen Liu<br><span class="muted">Cornell University · Stanford University</span></div><div class="venue">RSS 2026 · Based on arXiv v2, 24 February 2026</div></div><div class="cover-media"><img class="cover-video" src="assets/videos/cover_montage.gif" alt="Looping real-robot tool-use experiments with a brush, hammer, marker and spatula" decoding="async"><img class="cover-video-poster" src="assets/videos/cover_montage.jpg" alt="Real robot tool-use experiments with a brush, hammer, marker and spatula"><p>Real-world experiments: brush, hammer, marker and spatula</p></div>`,`The cover GIF loops through real robot experiments with a brush, hammer, marker and spatula. Use it to establish the physical setting before introducing the central question: how can one dexterous controller transfer across unfamiliar tools and goal trajectories? SimToolReal trains such a controller on simple synthetic tools in simulation. At deployment, human demonstrations provide object motion goals, while the robot decides how its own hand and arm should realize them. We will ask how to teach tool use, then formulate a pose-reaching problem and study its simulation-trained recurrent policy. Only after seeing simulation behavior will we introduce the real-world perception pipeline. Several looping experiment GIFs illustrate transfer before a short quantitative summary and discussion. The paper is listed in the RSS 2026 proceedings.`,undefined,'cover');

add('01 / Brainstorm','How would you teach a robot to use tools?',
'<p class="question">Suppose the robot must use<br>a new brush, hammer or spatula.<br><em>What would you build first?</em></p>'+
'<div class="brainstorm-routes">'+f('<h3>Collect robot demonstrations</h3>'+small('Learn a policy from action supervision.'),1)+f('<h3>Use a human demonstration</h3>'+small('Transfer the motion across embodiments.'),2)+f('<h3>Learn through simulation</h3>'+small('Let physical interaction shape the controller.'),3)+'</div>',
`Begin with the open question before revealing any choices. Give the audience time to suggest their own route. Reveal robot imitation, human retargeting and simulation learning as possible answers rather than an exhaustive or mutually exclusive taxonomy. A diffusion policy or VLA can use imitation learning. Ask what data each route needs, and how it handles grasping thin tools, in-hand rotation and forceful contacts. Then narrow the discussion to the demonstration bottleneck.`,
'Presenter brainstorm · Motivated by paper §I–II','brainstorm-slide');

add('01 / Motivation','What makes demonstration-based tool use difficult?',
p('Thin-object grasping, in-hand rotation and external forces make contact quality important.')+
cols(f('<h3>Robot action demonstrations</h3>'+list(['High-quality dexterous teleoperation is difficult.','Limited force feedback makes stable contacts hard to demonstrate.']),1),
f('<h3>Human motion retargeting</h3>'+list(['Human and robot fingers have different kinematics.','Matching hand motion does not ensure a physically stable grasp.']),2))+
f(call('What if a demonstration specified tool motion, while the robot learned how to realize it?'),3),
`The previous page leaves multiple routes open. Here explain the particular bottlenecks that motivate this paper. Robot action demonstrations directly match the robot but are costly to collect well in dexterous contact tasks. Human video is convenient, yet transferring finger motion does not guarantee feasible contacts. These limitations do not prove imitation learning or VLAs cannot solve the tasks. SimToolReal includes neither a strong learned IL nor a VLA baseline. Its alternative is to keep object-level guidance and learn the motor strategy in simulation.`,
'Paper §I–II · Motivation, not a general failure claim about IL');

add('02 / Method','Tool use as a sequence of pose-reaching problems',V.reduction()+f(call('Object goals specify the motion. RL discovers robot-specific grasps and in-hand actions.'),3),`This is the conceptual pivot. The human provides a sequence of rigid-tool configurations. A goal-conditioned controller learns how to move the tool between configurations using this robot's arm and hand. It is related to functional or object-centric retargeting, but the controller is trained in advance on randomized primitives rather than trained for each demonstration. The arrow from goals to policy denotes conditioning, not policy fine-tuning.`,`Paper §III-A · Presenter schematic`);

add('02 / Method','A 6D pose specifies position and orientation',V.pose()+f(eq(String.raw`g^k=(R^k,p^k)\in SE(3),\qquad \mathcal G=\{g^1,\ldots,g^K\}`,true),3),`A rigid object's pose has three translational and three rotational degrees of freedom. It need not be encoded as six Euler-angle coordinates; the paper uses keypoint-based features and distances. Reveal lift, reorientation and swing in order. This schematic is a task interface, not a measured demonstration. At runtime the policy receives the current goal. The goal sequence is spatial and event-driven, so the robot does not have to reproduce the human's timing.`,`Paper §III-A · Illustrative pose sequence, not experimental data`);

add('02 / Simulation','Training pipeline: learn pose reaching through interaction',V.simPipeline()+small('Procedural tools and random goals supply the training distribution. No human task trajectories enter this loop.'),
`This diagram is entirely in simulation. Randomized tool geometry, density, initial state and pose goals define the environments. The actor receives restricted observations, with noise and delay, and produces arm-hand actions. The simulator returns the next state and reward. Reveal the asymmetric critic: it sees exact simulator state and extra progress features during training only. SAPG, a PPO-family algorithm, uses a population for exploration and their collected experience to update a leader policy. The result is one reusable actor, not a task-specific policy trained after seeing a test demonstration. IsaacGym runs 24,576 parallel environments in the reported setup.`,
'Paper §III-B · Appendix C · Simplified simulation-only pipeline','sim-pipeline-slide');

add('02 / Simulation','SAPG splits exploration and aggregates experience',
p('One PPO policy can collect similar experience across thousands of parallel environments.')+
V.sapg()+
f(call('SAPG retains PPO-style actor–critic updates while changing how experience is explored and reused.'),2),
`SAPG stands for Split and Aggregate Policy Gradients. First reveal Split. The simulator environments are partitioned across a leader and multiple follower policies. Followers use different entropy regularization strengths, so the population covers different exploration–exploitation behaviors. Each policy collects its own dataset and followers still update from their own data with the usual PPO objective. Then reveal Aggregate. The leader combines its own on-policy dataset with sampled follower experience. Because the follower trajectories came from different policies, SAPG uses importance weighting in the off-policy part of the leader update. The final deployed policy is the leader. This is a simplified leader–follower schematic: pi 1 through pi M denotes a general population size rather than the exact number of boxes drawn. The main reason to use SAPG here is the exploration challenge created by high-dimensional dexterous actions and massively parallel simulation. Avoid describing SAPG as a new robot architecture or a replacement for actor–critic learning. It changes population-based data collection and experience aggregation around PPO-style optimization. Original method: Singla et al., Split and Aggregate Policy Gradients, ICML 2024, https://sapg-rl.github.io/resources/2024_icml_sapg.pdf. SimToolReal configuration: https://github.com/tylerlum/simtoolreal/blob/main/isaacsimenvs/cfg/train/SimToolRealSAPG.yaml`,
'Singla et al. · Split and Aggregate Policy Gradients · ICML 2024 · SimToolReal Appendix C','sapg-slide');

add('02 / Simulation','SAPG learns more effectively than PPO in this setting',
cols(
  fig(8,'Paper Fig. 8 · Training reward, mean over five seeds',376),
  f('<h3>Controlled comparison</h3>'+list(['Both runs retain the asymmetric critic.','Replacing SAPG with PPO changes the exploration and data aggregation scheme.']),1)+
  f('<h3>Observed result</h3>'+list(['SAPG continues improving across 9B environment steps.','PPO reaches a much lower plateau under the matched setup.']),2)
)+
f(small('The symmetric-critic ablation also performs poorly, so the result supports the combination rather than SAPG alone.'),2)+
small('Metric: simulation training reward, not real-world functional task completion.'),
`Read this as the evidence page for the previous SAPG mechanism. The clean SAPG-versus-PPO comparison uses the same asymmetric critic in both runs. The main change is the exploration and experience aggregation scheme: PPO uses a single policy's on-policy data, while SAPG distributes exploration across policies and uses importance-weighted follower experience in the leader update. Across the nine-billion-step ablation, SAPG keeps improving while PPO remains at a much lower reward. Do not claim that this isolates every training choice. The third curve removes the asymmetric critic while retaining SAPG and also performs poorly, so the paper supports the combined training recipe rather than proving that SAPG alone explains the full gain. The curves report simulation episode reward averaged over five seeds. They do not measure real-world task success or sample efficiency against every modern RL baseline.`,
'Simulation · Paper Fig. 8 · §IV-E');

add('02 / Method','Procedural tools cover shape and mass variation',V.primitives()+f(call('The commonality is a geometric interface: tool pose and a graspable region.'),1),`The authors do not train a semantic module to discover that all tools share a purpose. They choose a handle–head structural family and generate simple geometry with varied size and density. The policy receives a coarse grasp box, not a detailed mesh or an explicit estimate of mass and inertia. LSTM history helps infer unobserved properties through interaction. The small boxes shown here are schematic, not the actual distribution of sampled assets.`,`Paper §III-B · Procedural Asset Generation appendix · Presenter schematic`);

add('02 / Simulation','RL training signal: how each reward term is constructed',
eq(String.raw`r=r_{\mathrm{smooth}}+r_{\mathrm{grasp}}+\mathbb I_{\mathrm{grasped}}r_{\mathrm{goal}}`,true)+
`<div class="reward-grid">`+
f(`<div class="reward-term"><h3>1 · Smooth motion</h3>${eq(String.raw`r_{\rm smooth}=-\lambda_{\rm arm}\|\dot q_{\rm arm}\|_1-\lambda_{\rm hand}\|\dot q_{\rm hand}\|_1`,true)}<p>L1 penalties on current arm and hand joint velocities.</p></div>`,1)+
f(`<div class="reward-term"><h3>2 · Acquire the grasp</h3>${eq(String.raw`r_{\rm grasp}=r_{\rm approach}+(1-\mathbb I_{\rm grasped})r_{\rm lift}`,true)}${eq(String.raw`r_{\rm approach}=\lambda_{\rm approach}\max(d_{\rm ft}^*-\bar d_{\rm ft},0)`,true)}<p>Improvement in mean fingertip-to-object distance.</p>${eq(String.raw`r_{\rm lift}=\lambda_{\rm lift}\max(z-z_{\rm init},0)+B_{\rm lifted}\mathbb I[z\ge z_{\rm lifted}]`,true)}<p>Height progress plus a one-time lifted bonus.</p></div>`,2)+
f(`<div class="reward-term"><h3>3 · Reach each goal pose</h3>${eq(String.raw`r_{\rm goal}=\max(d^*-d(o_t,g),0)+B_{\rm succ}\mathbb I[d(o_t,g)<\epsilon]`,true)}<p><b>Progress:</b> reward improvement over the best distance so far.</p><p><b>Success:</b> bonus below ε, then sample the next goal.</p></div>`,3)+
`</div>`+
f(small(`Pose distance: ${katex.renderToString(String.raw`d(o_t,g)=\max_{i=1,\ldots,4}\|o_{t,i}-g_i\|_2`,{throwOnError:true})}. Four fixed-scale keypoints jointly encode translation and rotation.`),3)+
f(call('These are environment reward terms. SAPG still optimizes an actor–critic objective from the resulting returns.'),4),
`Use “reward” rather than “loss” for the three terms on this page. Start with smoothness: the method subtracts separate L1 norms of current joint velocities for the seven arm joints and twenty-two hand joints, weighted by lambda arm and lambda hand. Then reveal grasp shaping. The approach term is lambda approach times improvement in mean fingertip-to-object distance relative to the best value seen in the episode. The lift term rewards object height above its initial value and adds a one-time bonus after crossing the lift threshold. Multiplication by one minus I grasped disables lifting reward after the first successful lift. Finally reveal goal reaching. The method stores the smallest keypoint distance d star achieved for the current goal and rewards only further improvement, which prevents repeated reward for remaining statically near a target. Crossing epsilon adds a success bonus and resamples the next goal. Distance is the maximum Euclidean error over four fixed-scale object-frame keypoints, using 14 by 3 by 3 centimeter scales. This makes translation and rotation enter one metric and puts more sensitivity on pitch and yaw than roll along the tool's long axis. The outer I grasped activates goal reward only after lifting. Distinguish these environment rewards from the SAPG/PPO actor–critic optimization loss.`,
'Paper §III-B · Appendix A, Eqs. 3–9 · Table I','reward-detail-slide');

add('02 / LSTM policy','LSTM memory carries interaction history across steps',V.memory()+
`<div class="memory-state-grid">`+
f(`<div class="memory-state"><h3>Cell state c<sub>t</sub>: internal memory</h3>${eq(String.raw`c_t=f_t\odot c_{t-1}+i_t\odot\tilde c_t`,true)}<p>Forget gate f<sub>t</sub> retains old information. Input gate i<sub>t</sub> writes candidate memory.</p></div>`,3)+
f(`<div class="memory-state"><h3>Hidden state h<sub>t</sub>: current representation</h3>${eq(String.raw`h_t=o_t\odot\tanh(c_t)`,true)}<p>Output gate o<sub>t</sub> exposes information to the action MLP and the next time step.</p></div>`,4)+
`</div>`+
f(small('Both states have 1,024 dimensions. They carry a learned summary of history rather than a stack of raw past frames.'),5),
`Read the unrolled network from left to right. At time t, the same LSTM receives the current feature vector x t, the previous hidden state h t minus 1 and the previous cell state c t minus 1. The feature vector already bundles the deployable object-centric interface introduced in the simulation pipeline: robot proprioception and the previous joint target, plus tool orientation, palm-relative keypoints, goal-keypoint errors and grasp-box dimensions. It excludes the detailed mesh, explicit mass and inertia, and privileged object velocity. The LSTM outputs updated states h t and c t. The action MLP reads h t to produce the current 29-dimensional action. The cell state is the internal memory channel. In the standard LSTM update shown here, the forget gate f t decides how much of c t minus 1 to retain, while the input gate i t decides how much candidate memory c tilde t to write. The hidden state is the currently exposed representation. The output gate o t selects which information from the updated cell state reaches h t. Both states have 1,024 dimensions in this policy. The diagram does not mean that the model receives a literal stack of past frames or outputs historical actions. History affects the current decision through the recurrent states, while the previous joint target also enters the observation explicitly. The authors motivate recurrence as a way to infer latent physical and geometric properties through interaction. This is an architectural rationale, not evidence that individual hidden units encode an identifiable mass estimate. The unrolled diagram represents one shared recurrent policy, not three separately trained policies. The gate equations are the standard LSTM mechanism and are included for explanation; the paper does not claim gate-level novelty. The MLP hidden widths are 1,024, 1,024, 512 and 512 before 29 action outputs. The official configuration uses one LSTM layer, layer normalization and ELU in the MLP. Configuration snapshot: https://github.com/tylerlum/simtoolreal/blob/313d5aea1f507c6cfe097b672b62945d7b0bbff5/isaacgymenvs/cfg/train/SimToolRealLSTMAsymmetricPPO.yaml`,
'Paper §III-B · Table I · Standard recurrent-state schematic','memory-slide');

add('02 / LSTM policy','The action head controls the arm and hand differently',
eq(String.raw`a_t=\big[a_t^{\mathrm{arm}},a_t^{\mathrm{hand}}\big]\in[-1,1]^{29}`,true)+
cols('<h3>7 arm joints: incremental targets</h3>'+eq(String.raw`\hat q_t^{\rm arm}=q_{t-1}^{\rm target,arm}+0.025a_t^{\rm arm}`,true)+p('Each action adjusts the previous target.'),
'<h3>22 hand joints: absolute targets</h3>'+eq(String.raw`\hat q_t^{\rm hand}=q_{\min}+\frac{a_t^{\rm hand}+1}{2}\odot(q_{\max}-q_{\min})`,true)+p('Each action maps into the joint’s allowed range.'))+
f(call('Joint limits and EMA smoothing (α = 0.1) produce the final targets at 60 Hz.'),1)+small('The deployed actor keeps its weights fixed. Recurrent state updates at every control step.'),
`The network output is not a Cartesian tool displacement or a direct torque command. After clipping to minus one through one, the seven arm components are incremental changes from previous joint targets, with the reported scale 0.025. The 22 hand components map to absolute joint limits. Both streams use exponential moving average smoothing with alpha 0.1. The exact clipping order differs: arm targets are clipped before smoothing, while hand targets are clipped after smoothing. The important distinction is online memory update versus weight update. Hidden and cell states change as observations arrive, but policy parameters do not adapt at deployment. This permits feedback control without task-specific training.`,
'Paper Appendix C.2 · Eqs. 10–11 · Table I','action-slide');

add('02 / Simulation','Simulation: reaching diverse tool poses',videoSlide('training','SimToolReal project: training environment',[
'The <strong>green mesh</strong> indicates the current target pose.',
'The policy learns to acquire and reorient procedurally generated tools.',
'There is no human task trajectory in this training loop.']),`The training GIF loops automatically. Direct attention to the changing relationship between fingers and object as the policy reaches targets. The green object is a target visualization, not a second physical object. This clip illustrates what the training environment looks like. It does not independently quantify training efficiency or prove generalization.`,`Official project video · training.gif converted from training.mp4 · Paper §III-B`);

add('03 / Sim-to-real','Simulation exposes the state. Reality requires estimation.',
cols('<h3>Inside the simulator</h3>'+list(['Exact tool pose and geometry are available.','Random goal poses define the task.','Noise and delays train the actor on imperfect inputs.']),
f('<h3>On the real robot</h3>'+list(['The tool pose is hidden behind pixels and occlusion.','A human demonstration supplies a meaningful trajectory.','Perception must recover the same policy interface.']),1))+
f(call('Keep the motor policy fixed. Replace simulator-derived inputs with measured and estimated inputs.'),2),
`Use the simulation video as the transition. The simulator exposes exact state, although the actor was deliberately trained with corrupted observations and the critic had the clean state. At deployment, neither the current pose nor a new tool's geometry comes from a simulator. They must be estimated. Random goals also need to become a useful task sequence. A human demonstration specifies that sequence. This motivates the real-world setup and tracking modules on the next page. Zero-shot means transferring the policy without target-tool or target-task training, not removing demonstrations, calibration or perception.`,
'Paper §III-B–C · The actor trains with noise and delay despite simulator ground truth');

add('03 / Deployment','Real deployment supplies the same policy interface',V.deployment(),
`This is the first full real-world deployment pipeline. During setup, a human RGB-D demonstration supplies the tool and desired motion. User-prompted SAM 2 segmentation and SAM 3D, using captured depth, recover a metric mesh and grasp box. FoundationPose tracks the mesh through the video to extract goals. During online execution, a fresh RGB-D stream and that mesh supply the live pose. The fixed actor receives this pose, proprioception, the grasp box and the current goal. Its actions close the physical loop. The mesh belongs to perception and is not fed directly into the actor. No policy training takes place in this pipeline. The grasp box and mesh are setup outputs reused throughout an episode.`,
'Paper §III-C · Appendix E · Simplified redraw of real deployment','deployment-slide');

add('03 / Deployment','The robot advances goals only after reaching them',V.loop()+f(small('3 Hz is waypoint sampling. Goal switching is event-driven, while the controller runs at 60 Hz.'),3),`The setup is semi-automated: user point prompts identify the tool and handle/head, SAM 3D uses captured depth for metric scale, and FoundationPose extracts the demonstrated trajectory and tracks the live tool. Separate the three rates explicitly. Human trajectory processing downsamples a 30 Hz video trajectory to 3 Hz waypoints and trims its stationary pre-grasp portion. The live pose tracker updates at 30 Hz. Robot control runs at 60 Hz. The active goal changes only after the pose error falls below the threshold, not every one-third of a second. The robot may therefore take longer to execute a difficult transition than the person did. Zero-shot means no target-tool or target-trajectory policy training. A demonstration, geometry setup and live sensing are still required.`,`Paper §III-C · Table I · Goal Pose Sequence appendix · Presenter schematic`);

add('03 / Deployment','The closed loop follows unseen tool trajectories',videoSlide('inference','SimToolReal project: real-world inference',[
'The human demonstration supplies the <strong>tool-motion goals</strong>.',
'The fixed policy grasps, reorients and moves the real brush.',
'The goal interface specifies tool motion rather than robot finger trajectories.']),`The looping project GIF places the human demonstration and extracted goal poses alongside real robot execution. Use it to connect the two branches of the pipeline. The robot policy does not update its weights on this new trajectory. Goal progression is event-driven, as described on the preceding slide. Treat the rendered goal display as an explanatory visualization, not additional evidence from a digital-twin experiment.`,`Official project video · inference.gif converted from inference.mp4 · Paper §III-C`);

add('04 / Real-world behavior','Brush and hammer: reorientation before interaction',
pair([['brush','Brush','Reorient the handle, then sweep along the surface.'],['hammer','Hammer','Change the grasp–tool orientation before the swing.']]),
`The brush and hammer GIFs loop side by side so the audience can compare finger motion without manual playback. Ask what the recurrent controller must do beyond moving the wrist. Both require acquiring a tool and changing its orientation relative to the hand. These author-provided category montages show real behavior at original speed. They are illustrative selections rather than random evaluation samples. Do not infer impact force or aggregate reliability from the montage.`,
'Real robot · Looping GIFs converted from official category videos · 1× speed · Qualitative examples','paired-video-slide');

add('04 / Real-world behavior','Marker and eraser: tool motion along a surface',
pair([['marker','Marker','Acquire a thin tool and move its tip across the board.'],['eraser','Eraser','Maintain a grasp while following a wiping path.']]),
`Compare the geometry and contact demands in the two clips. A marker is thin and requires tip positioning, whereas an eraser presents a larger contact region. The same actor handles both through the pose and grasp-region interface. The human supplies the demonstrated trajectory and perception supplies the tool state. The policy has no explicit representation of ink or erasing quality. Visible writing and wiping illustrate behavior but do not turn the benchmark pose-progress metric into a functional-success measure.`,
'Real robot · Looping GIFs converted from official category videos · 1× speed · Qualitative examples','paired-video-slide');

add('04 / Real-world behavior','Spatula and screwdriver: larger orientation changes',
pair([['spatula','Spatula','Serving and flipping demand changing tool orientation.'],['screwdriver','Screwdriver','Reorient and spin the tool in free space.']]),
`These clips emphasize orientation control, especially large flips and continuous rotations. Ask the audience to watch whether the fingers change contact while the tool turns. The benchmark includes serving or flipping with spatulas and free-space spinning with screwdrivers. It does not evaluate fastening a screw. The screwdriver is also a challenging case for visual tracking because symmetry can make orientation ambiguous. These examples motivate both the compact pose interface and its limitations for force-sensitive functional tasks.`,
'Real robot · Looping GIFs converted from official category videos · Screwdriver task is free-space spinning','paired-video-slide');

add('04 / Evidence','Real-world transfer across six tool categories',small('<b>12 objects · 24 object–task variations · 120 rollouts</b><br>Task Progress = fraction of sequential pose goals reached.')+V.performance()+small(`Mean progress: <b>${V.mean(V.results.flatMap(r=>r[3])).toFixed(1)}%</b>. This metric does not establish functional task success.`),
`DexToolBench evaluates six categories with two instances and two trajectories each, using five rollouts per variation. This chart recomputes category means from all 120 published rollout values. The evaluation threshold is 2 cm maximum pose-keypoint error, combining translation and rotation. Erasers need less in-hand rotation, while screwdrivers require reorientation and spinning. The overall mean is 79.3% trajectory progress, not 79.3% completed tasks. Screwdriver trials involve free-space spinning rather than screw insertion or tightening. Source rounding may affect the last decimal.`,
'Real robot · Presenter aggregation of Table II · 20 trials per category','results-slide');

add('04 / Scope','Recovery illustrates feedback, with clear limits',videoSlide('recovery','SimToolReal project: recovery behavior',[
'The policy can attempt to <strong>regrasp</strong> after an error.',
'Recovery depends on the tool staying <strong>reachable and trackable</strong>.',
'Rigid pose goals leave force objectives, clutter and task replanning unresolved.'
]),`The recovery GIF loops automatically and brings the emphasis back from average performance to the role of feedback. The authors observe regrasp attempts even though training resets after drops. Keep the claim conditional: useful state feedback and a reachable object remain necessary. The policy does not explicitly plan around scene obstacles or optimize functional contact forces. Rigid tools and a fixed goal sequence also limit the scope. These qualifications motivate the three research inspirations on the next page. A selected recovery clip is not a systematic robustness evaluation.`,
'Looping GIF converted from the official recovery video · Paper §IV-A and §V · Qualitative behavior');

add('05 / Discussion','Structured simulation as a route to reusable robot skills',
`<div class="scope-label">Presenter reflection · Not results established by this paper</div>
<div class="closing-thesis"><div class="eyebrow">01 · Primary takeaway</div><p class="closing-statement">Beyond scaling end-to-end action models, <span>structured simulation</span> may offer another path toward skill acquisition in the wild.</p><p class="closing-support">RL learns reusable motor competence. Perception, demonstrations or a higher-level model specify what the tool should do.</p></div>
<div class="closing-directions">${f('<h3>02  Compact interfaces beyond tool use</h3><p>Other interactions may admit a useful task interface, although pose alone will not always suffice. Contact, force, articulation or shape may need to enter the state.</p>',1)}${f('<h3>03  Lightweight VLMs for semantic setup</h3><p>A VLM could select tools, grasp regions and subgoals, while geometric perception retains metric, low-latency tracking.</p>',2)}</div>
<p class="closing-caveat">SimToolReal demonstrates the motor-skill component inside a designed interface. Autonomous task and goal discovery remain open.</p>`,
`Close with the user's three inspirations in one hierarchy rather than a Discussion page followed by a repetitive Takeaway. The first point is the main conclusion: structured simulation and reusable motor controllers may complement scaling large action models. SimToolReal establishes transfer in a structured setup, not autonomous online skill acquisition in the wild. Then reveal two extensions. The deeper idea behind the second point is to search for sufficient task interfaces. Rigid SE(3) poses will not capture articulated state, deformation, force or all scene constraints. The third point assigns lightweight VLMs to semantic setup, tool selection and subgoal generation, while metric pose tracking remains geometrically grounded. Replacing the tracker directly would require evidence on pose error, latency and failure behavior. A controlled follow-up could freeze the actor and compare manual prompts with VLM region proposals, measuring setup effort and functional completion.`,
'Presenter discussion · Main reflection and two research extensions','closing-slide');

add('Backup','References, videos and source material',`<div class="references"><p><b>Main paper</b><br>Kedia, Lum, Bohg and Liu. <i>SimToolReal: An Object-Centric Policy for Zero-Shot Dexterous Tool Manipulation.</i><br><a href="https://arxiv.org/abs/2602.16863v2">arxiv.org/abs/2602.16863v2</a> · <a href="https://www.roboticsproceedings.org/rss22/p151.html">RSS 2026 proceedings</a></p><p><b>Project and code</b><br><a href="https://simtoolreal.github.io/">simtoolreal.github.io</a> · <a href="https://github.com/tylerlum/simtoolreal">github.com/tylerlum/simtoolreal</a></p><p><b>Closely related work</b><br>Chen et al. <i>Object-Centric Dexterous Manipulation from Human Motion Data.</i> CoRL 2024.<br>Lum et al. <i>Crossing the Human-Robot Embodiment Gap with Sim-to-Real RL Using One Human Demonstration.</i> 2025.<br>Singla et al. <i>Split and Aggregate Policy Gradients.</i> ICML 2024.<br>Petrenko et al. <i>DexPBT.</i> 2023.</p><p><b>Design reference</b><br><a href="https://github.com/Mizoreww/steerable-vla-talk">Mizoreww/steerable-vla-talk</a> and the previous A2A seminar deck.</p></div>`,`Paper figures and project videos retain their original authorship. Custom diagrams are explanatory schematics. The SAPG page simplifies the leader–follower data flow from Singla et al., ICML 2024. Real-world aggregate charts derive from the published Table II data, provided in CSV form alongside this deck. The discussion section explicitly labels untested extensions. The package also contains English speaker notes and a detailed Chinese narrative assessment.`,`Sources and attribution`);

const css=await fs.readFile(out+'/src/style.css','utf8'),nav=await fs.readFile(out+'/src/navigation.js','utf8');
const html=slides.map((s,i)=>`<section class="slide ${s.cls} ${i===0?'active':''}" data-no="${i+1}">${s.cls==='cover'?s.body:`<header class="head"><div class="section-label">${s.section}</div><h2>${s.title}</h2><div class="rule"></div></header><div class="body">${s.body}</div>`}<div class="brand">SIMTOOLREAL</div><div class="pageno">${String(i+1).padStart(2,'0')} / ${slides.length}</div><div class="build-count"></div><footer class="cite">${s.source}</footer><aside class="notes-hidden">${s.note}</aside></section>`).join('\n');
await fs.writeFile(out+'/slides.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SimToolReal · Research Seminar</title><link rel="stylesheet" href="assets/katex/katex.min.css"><style>${css}</style></head><body><main id="canvas">${html}</main><div id="lightbox"><img id="lightbox-img" alt="Enlarged paper figure"><div class="hint">Click or press Escape to close</div></div><nav id="hud"><button id="prev">◀</button><span><span id="cur"></span> / <span id="tot"></span></span><button id="next">▶</button><button id="all">Reveal · A</button><button id="full">Fullscreen · F</button><a href="index.html" target="_blank">Notes</a></nav><div id="progress"></div><script>${nav}</script></body></html>`);
if(zhNotes.length!==slides.length||zhNotes.some((n,i)=>n.title!==slides[i].title))throw new Error('Chinese script is not aligned with the slide deck');
await fs.writeFile(out+'/speaker_notes.md','# SimToolReal · English Speaker Notes\n\nSuggested duration: 31–36 minutes including looping GIFs, plus discussion. Slides 1–23 are the main talk. Slide 24 is the reference backup. Use Right / Space for step reveals, A to reveal a whole page, and F for fullscreen. Experiment GIFs loop automatically, are silent and preserve the original playback speed.\n\n'+slides.map((s,i)=>`## ${i+1}. ${s.title}\n\n${s.note}\n\nSource: ${s.source}`).join('\n\n'));
await fs.writeFile(out+'/speaker_notes_zh.md','# SimToolReal 中文逐页汇报稿\n\n建议时长：正文 31–36 分钟（含循环 GIF 展示），另加讨论。第 1–23 页为正文，第 24 页为来源备份页。每页均与 slides.html 的页码和英文标题严格对应。\n\n'+zhNotes.map((n,i)=>`## ${i+1}. ${n.zhTitle}\n\n**对应英文标题：** ${n.title}\n\n**建议时间：** ${n.timing}\n\n${n.script}\n\n${n.cue?`**操作提示：** ${n.cue}\n`:''}`).join('\n'));
await fs.writeFile(out+'/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SimToolReal · Presenter Notes</title><style>body{background:#edf2ef;margin:0;font:18px/1.7 Arial,sans-serif;color:#283531}main{max-width:1000px;margin:auto;background:white;padding:55px}h1{font:54px Georgia,serif;color:#1d7d76}h2{font:28px Georgia,serif}a{color:#1d7d76}section{border-top:1px solid #d6e5e1;padding:25px 0}.source{font-size:13px;color:#71847e}ol{columns:2;font-size:15px}@media(max-width:700px){main{padding:25px}ol{columns:1}}</style><main><h1>SimToolReal</h1><p>Presenter materials · 31–36 minute methodology-focused seminar</p><p><a href="slides.html">Open presentation</a> · <a href="SimToolReal_slides.pdf">PDF</a> · <a href="speaker_notes_zh.md">Chinese slide-matched script</a> · <a href="speaker_notes.md">English notes</a> · <a href="paper/narrative_assessment_zh.md">Narrative assessment (Chinese)</a></p><p>Right / Space: next build. Left: previous build. A: reveal all. F: fullscreen. Experiment GIFs loop automatically and remain silent. Click figures to enlarge; Escape closes them. PDF shows the complete builds and static poster frames.</p><ol>${slides.map((s,i)=>`<li><a href="#s${i+1}">${s.title}</a></li>`).join('')}</ol>${slides.map((s,i)=>`<section id="s${i+1}"><div class="source">SLIDE ${i+1} · ${s.section}</div><h2><a href="slides.html#${i+1}">${s.title}</a></h2><p>${s.note}</p><div class="source">${s.source}</div></section>`).join('')}</main></html>`);
await fs.writeFile(out+'/src/deck-data.json',JSON.stringify(slides,null,2));
await fs.writeFile(out+'/paper/real_world_results.csv','category,instance,trajectory,r1,r2,r3,r4,r5,mean_progress\n'+V.results.map(r=>[...r.slice(0,3),...r[3],V.mean(r[3]).toFixed(2)].join(',')).join('\n')+'\n');
console.log('Built',slides.length,'slides. Overall Task Progress:',V.mean(V.results.flatMap(r=>r[3])).toFixed(3));

await fs.writeFile(out+'/assets/system_architecture.svg',V.architecture().replace('<defs>','<style>text{font-family:Arial,Helvetica,sans-serif}</style><defs>'));

for(const [name,draw] of [['simulation_pipeline',V.simPipeline],['sapg',V.sapg],['deployment_pipeline',V.deployment],['lstm_memory',V.memory]])await fs.writeFile(out+'/assets/'+name+'.svg',draw().replace('<defs>','<style>text{font-family:Arial,Helvetica,sans-serif}</style><defs>'));
