import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import katex from 'katex';
import * as V from './visuals.mjs';
const out=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const p=s=>`<p class="lead">${s}</p>`,small=s=>`<p class="small">${s}</p>`;
const f=(s,n=1)=>`<div class="fragment" data-step="${n}">${s}</div>`;
const call=(s,w=false)=>`<div class="callout${w?' warm':''}">${s}</div>`;
const cols=(a,b,wide=false)=>`<div class="cols${wide?' wide':''}"><div>${a}</div><div>${b}</div></div>`;
const list=a=>`<ul class="bul">${a.map(s=>`<li>${s}</li>`).join('')}</ul>`;
const eq=(s,sm=false)=>`<div class="equation${sm?' sm':''}">${katex.renderToString(s,{displayMode:true,throwOnError:true})}</div>`;
const fig=(n,c,h=370)=>`<figure class="paperfig"><img src="assets/fig${String(n).padStart(2,'0')}.png" alt="${c}" style="max-height:${h}px"><figcaption>${c}</figcaption></figure>`;
const table=(heads,rows,compact=false)=>`<table class="tb${compact?' compact':''}"><thead><tr>${heads.map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr class="${String(r[0]).startsWith('SimToolReal')?'highlight':''}">${r.map(x=>`<td><span>${x}</span></td>`).join('')}</tr>`).join('')}</tbody></table>`;
const video=(n,c)=>`<div class="video-wrap"><video controls muted playsinline preload="none" poster="assets/videos/${n}.jpg" aria-label="${c}"><source src="assets/videos/${n}.mp4" type="video/mp4"></video><img class="video-poster" src="assets/videos/${n}.jpg" alt="Video still: ${c}"><div class="video-caption"><span>${c} · 1× speed · silent excerpt</span><a href="https://simtoolreal.github.io/">Original project video ↗</a></div></div>`;
const videoSlide=(name,c,cues)=>cols(video(name,c),`<div class="stack"><div class="eyebrow">What to watch</div>${cues.map(s=>`<p class="video-cue">${s}</p>`).join('')}</div><button class="play-video">Play / pause · V</button>`,true);
const steps=a=>`<div class="number-list">${a.map((r,i)=>`<span class="num">0${i+1}</span><div><h3>${r[0]}</h3><p>${r[1]}</p></div>`).join('')}</div>`;
const slides=[];
const add=(section,title,body,note,source='Kedia et al. · SimToolReal · arXiv:2602.16863v2',cls='')=>slides.push({section,title,body,note,source,cls});
add('','SimToolReal',`<div class="cover-bar"></div><div class="cover-copy"><div class="eyebrow">Research seminar</div><h1>SimTool<span class="teal">Real</span></h1><div class="subtitle">An Object-Centric Policy for<br>Zero-Shot Dexterous Tool Manipulation</div><p class="cover-question">Can one reusable controller<br>turn tool motion into robot skill?</p><div class="authors">Kushal Kedia* · Tyler Ga Wei Lum*<br>Jeannette Bohg · C. Karen Liu<br><span class="muted">Cornell University · Stanford University</span></div><div class="venue">RSS 2026 · Based on arXiv v2, 24 February 2026</div></div><img class="cover-art" src="assets/fig13.png" alt="Real tools and their reconstructed meshes">`,`The central question is how to reuse a dexterous controller across unfamiliar tools and goal trajectories. SimToolReal trains such a controller on simple synthetic tools in simulation. At deployment, human demonstrations provide object motion goals, while the robot decides how its own hand and arm should realize them. We will first compare learning routes, then explain the abstraction and pipeline, examine the evidence, and end with three research hypotheses. The paper is listed in the RSS 2026 proceedings.`,undefined,'cover');
add('01 / Motivation','Everyday tools demand dexterous control',videoSlide('brush','SimToolReal project: brush manipulation',[
'The tool extends what the robot can do.',
'The hand must establish a grasp, change the tool orientation, and maintain contact.',
'<strong>Question:</strong> how should a robot acquire this capability?']),`Play a short segment and ask the audience to watch the relation between the tool and fingers rather than only the arm path. A brush task bundles several behaviors that are often studied separately. The clip is an illustrative author-provided demonstration, not an aggregate performance measure. Pause after the manipulation becomes clear and pose the technical-route question.`,`Official project video · Brush_1080p_compressed.mp4`);
add('01 / Motivation','Tool use combines several contact problems',videoSlide('difficulty','SimToolReal project: why tool manipulation is hard',[
'<strong>Acquire:</strong> grasp a thin tool on a flat surface.',
'<strong>Reorient:</strong> move it within the fingers.',
'<strong>Interact:</strong> resist external forces without losing the tool.']),`This short author video motivates why tool manipulation is more than moving the end effector. Thin objects constrain initial finger placement. Large orientation changes can exceed the arm workspace under a fixed grasp. Tool-environment contact adds forces and torques. Multi-fingered hands offer contact choices but make teleoperation and learning harder. These difficulties motivate the comparisons on the next pages.`,`Paper §I · Official project video ToolManipHard.mp4`);
add('01 / Motivation','How could a robot learn to use a new tool?',`<div style="padding:36px 0 10px"><p class="question">Would you collect more data,<br>build a task simulator,<br>or change <em>what the policy learns</em>?</p></div>`+f(call('The design choice is both a learning method and an interface between the task and the robot.'),1),`Pause here before revealing the last sentence. Invite concrete suggestions: teleoperated demonstrations, human video, a pretrained action model, planning, or reinforcement learning. These are not mutually exclusive. The comparison is meant to identify where data collection, correspondence, contact reasoning, and task-specific engineering enter the pipeline.`,`Presenter framing based on §I–II`);
add('01 / Motivation','Several routes place the burden in different places',table(['Route','What supplies the behavior?','Main burden for dexterous tools'],[
['Robot demonstrations / IL','Observed robot actions<br>BC, diffusion or VLA policy','High-quality contact-rich data'],
['Human video / retargeting','Human hand or object motion','Embodiment gap and physical contact'],
['Planning + fixed grasp','Geometry and motion constraints','Feasibility under a rigid hand–tool relation'],
['Task-specific sim-to-real RL','Physics, a task model and reward','Object modeling and per-task training']])+f(call('SimToolReal combines human object-motion goals with a reusable controller learned in simulation.'),1),`This is a conceptual taxonomy, not an experimental leaderboard. Diffusion describes a policy parameterization or generative mechanism, imitation learning describes the learning signal, and a VLA describes an architecture and conditioning interface. They do not form disjoint alternatives. SimToolReal itself combines video-derived guidance, learned perception, and reinforcement learning. Its distinctive choice is to reuse one goal-reaching controller across objects and trajectories.`,`Conceptual comparison · Paper §I–II · No direct IL/VLA baseline in this paper`);
add('01 / Motivation','Imitation learning needs the right action data',cols(`<h3>Robot action supervision</h3>${p('Teleoperation supplies examples of what this robot should do.')}${f(list(['Hand kinematics differ across embodiments.','Limited force feedback makes dexterous contacts difficult to demonstrate.']),1)}`,`<h3>Human video supervision</h3>${p('A person can demonstrate the desired tool motion naturally.')}${f(list(['Human finger motion need not transfer to robot fingers.','Kinematic similarity does not guarantee a stable grasp.']),2)}`)+f(call('Can we transfer the desired object motion while letting the robot discover its own contact strategy?'),3),`Explain the difference between learning from robot actions and using a human video to specify the outcome trajectory. The paper argues that collecting high-quality dexterous teleoperation data is difficult. That is not evidence that imitation learning or VLAs cannot solve these tasks, and the paper does not compare against strong modern learned action baselines. The narrower question is whether object motion can serve as an easier-to-transfer interface.`,`Paper §I–II · Motivation, not a universal claim about IL`);
add('01 / Motivation','Reinforcement learning shifts the engineering cost',cols(`<h3>Why simulate?</h3>${list(['Physics exposes contact consequences.','Parallel trials explore grasp and reorientation strategies.','No robot action demonstrations are required for policy training.'])}`,`<h3>Why is reuse difficult?</h3>${list(['A new object may need a new simulation asset.','A new task may need a new reward.','A specialist can overfit to one trajectory.'])}`)+f(call('The paper asks whether many tool tasks can share one training objective.'),1),`The motivation is to amortize learning across tool-like objects rather than train a specialist after receiving each new demonstration. Simulation does not eliminate engineering: the robot model, randomization, reward shaping, safety constraints and perception pipeline still need design. What the authors remove is target-object and target-trajectory policy training at deployment.`,`Paper §I–III`);
add('02 / Core idea','The transferable interface is the tool motion',V.reduction()+f(call('Object goals specify the motion. RL discovers robot-specific grasps and in-hand actions.'),3),`This is the conceptual pivot. The human provides a sequence of rigid-tool configurations. A goal-conditioned controller learns how to move the tool between configurations using this robot's arm and hand. It is related to functional or object-centric retargeting, but the controller is trained in advance on randomized primitives rather than trained for each demonstration. The arrow from goals to policy denotes conditioning, not policy fine-tuning.`,`Paper §III-A · Presenter schematic`);
add('02 / Core idea','A 6D pose specifies position and orientation',V.pose()+f(eq(String.raw`g^k=(R^k,p^k)\in SE(3),\qquad \mathcal G=\{g^1,\ldots,g^K\}`,true),3),`A rigid object's pose has three translational and three rotational degrees of freedom. It need not be encoded as six Euler-angle coordinates; the paper uses keypoint-based features and distances. Reveal lift, reorientation and swing in order. This schematic is a task interface, not a measured demonstration. At runtime the policy receives the current goal. The goal sequence is spatial and event-driven, so the robot does not have to reproduce the human's timing.`,`Paper §III-A · Illustrative pose sequence, not experimental data`);
add('02 / Core idea','A single policy repeatedly solves goal reaching',eq(String.raw`a_t=\pi_\theta(s_t,o_t,\phi,g^k)`)+table(['Input','Meaning'],[['sₜ','Robot proprioception'],['oₜ','Estimated current tool pose'],['φ','Coarse grasp-region bounding box'],['gᵏ','Current desired tool pose']],true)+f(call('Reach the current pose, advance the goal, and reuse the same policy.'),1),`The compact notation hides recurrent history in the LSTM. The policy acts on proprioception, object pose, a coarse grasp-region descriptor and the current goal. It produces actions that become arm and hand joint-position targets. The abstraction reduces task specification complexity without claiming that all tool interaction physics are determined by pose. This distinction will return when we discuss task completion and force.`,`Paper §III-A–B · Recurrent state omitted from compact notation`);
add('02 / Core idea','Common structure is a designed prior',V.primitives()+f(call('The commonality is a geometric interface: tool pose and a graspable region.'),1),`The authors do not train a semantic module to discover that all tools share a purpose. They choose a handle–head structural family and generate simple geometry with varied size and density. The policy receives a coarse grasp box, not a detailed mesh or an explicit estimate of mass and inertia. LSTM history helps infer unobserved properties through interaction. The small boxes shown here are schematic, not the actual distribution of sampled assets.`,`Paper §III-B · Procedural Asset Generation appendix · Presenter schematic`);
add('03 / Method','Training varies objects and goals together',V.training()+f(call('The policy must grasp from the table before it can earn repeated goal-reaching rewards.'),3),`At reset the environment samples an object and robot initialization. The first goal can require a large motion or reorientation. Subsequent goals are near the preceding one, encouraging trajectory-like transitions. Unlike test-time demonstrations, these training goals are randomly generated. Procedural object diversity broadens the contact and inertial situations the policy encounters. IsaacGym provides 24,576 parallel environments in the reported configuration.`,`Paper §III-B · Table I · Presenter schematic`);
add('03 / Method','A shared reward induces the component skills',eq(String.raw`r=r_{\mathrm{smooth}}+r_{\mathrm{grasp}}+\mathbb I_{\mathrm{grasped}}r_{\mathrm{goal}}`)+steps([
['Approach and lift','Shaping helps the hand acquire the object from the table.'],
['Reach a pose','Reward improvement in pose distance and give a success bonus.'],
['Repeat','After success, sample another goal with the same reward.']])+f(call('“Universal objective” still includes engineered grasping and smoothness terms.'),1),`Avoid calling this reward-free learning or a single pure pose loss. The full reward includes smoothness and grasp shaping. The goal reward uses improvement over the best distance achieved so far rather than rewarding static proximity, and a large success bonus promotes completion. Once lifted, repeated random pose reaching induces reorientation and stable grasping behavior. The appendix contains the complete coefficients.`,`Paper §III-B · Eq. 1–2 · Reward Function Details appendix`);
add('03 / Method','Learning and transfer need more than object diversity',cols(`<h3>Learning in simulation</h3>${list(['SAPG improves exploration over the tested PPO setup.','An asymmetric critic uses privileged simulator state.','An LSTM actor handles partial observations.'])}`,`<h3>Deploying in reality</h3>${list(['Randomize pose noise and sensing delays.','Perturb the object with forces and torques.','Match robot dynamics and smooth the joint targets.'])}`)+f(call('The deployed actor only sees signals that the real system can provide.'),1),`SAPG is Split and Aggregate Policy Gradients, a PPO-family method that maintains exploratory policies and aggregates experience. The critic receives clean states and additional physical information unavailable to the deployed actor. Domain randomization targets real observation and actuation imperfections. The paper's ablations establish the importance of SAPG and the asymmetric critic in its setup, not the superiority of this optimizer in all settings.`,`Paper §III-B · Sim-to-Real Details appendix`);
add('03 / Method','Training on synthetic tools produces dexterous motion',videoSlide('training','SimToolReal project: training environment',[
'The <strong>green mesh</strong> indicates the current target pose.',
'The policy learns to acquire and reorient procedurally generated tools.',
'There is no human task trajectory in this training loop.']),`Play the training excerpt. Direct attention to the changing relationship between fingers and object as the policy reaches targets. The green object is a target visualization, not a second physical object. This clip illustrates what the training environment looks like. It does not independently quantify training efficiency or prove generalization.`,`Official project video · training.mp4 · Paper §III-B`);
add('03 / Method','Deployment adds perception and a human demonstration',fig(3,'Paper Fig. 3 · Human video processing and online policy execution',382)+f(call('The policy is fixed. A new demonstration supplies tool geometry and goal poses.'),1),`Walk through the left side first. RGB-D imagery supplies an object mesh, a grasp region and a tool trajectory. Then move to the right side, where online pose estimates and proprioception close the loop around the same pretrained policy. A mesh is still acquired for the new real object, but it is used in perception, not to retrain a target-object simulator policy.`,`Paper Fig. 3 · §III-C`);
add('03 / Method','Geometry extraction is semi-automated',fig(12,'Paper Fig. 12 · Metric mesh, handle/head segmentation and grasp box',344)+f(call('SAM 2 uses user point prompts. SAM 3D uses captured depth for metric scale.'),1)+f(small('The handle defines the grasp box and canonical frame. FoundationPose then tracks the tool.'),2),`The appendix qualifies any claim of fully automatic tool understanding. The user points to the target object and then to handle/head regions in rendered views. SAM 2 propagates masks. SAM 3D reconstructs a mesh using captured depth rather than relying on predicted monocular scale. The handle and head establish the grasp-region box and canonical coordinate frame. The paper uses vision foundation models already, so it should not be framed as a foundation-model-free system.`,`Human Video Processing appendix · Fig. 12`);
add('03 / Method','Goal switching is event-driven',V.loop()+f(small('3 Hz describes demonstration downsampling, not the policy control frequency.'),3),`Separate the three rates explicitly. Human trajectory processing downsamples a 30 Hz video trajectory to 3 Hz waypoints and trims its stationary pre-grasp portion. The live pose tracker updates at 30 Hz. Robot control runs at 60 Hz. The active goal changes only after the pose error falls below the threshold, not every one-third of a second. The robot may therefore take longer to execute a difficult transition than the person did.`,`Paper §III-C · Table I · Goal Pose Sequence appendix · Presenter schematic`);
add('03 / Method','The closed loop follows unseen tool trajectories',videoSlide('inference','SimToolReal project: real-world inference',[
'The human demonstration supplies the <strong>tool-motion goals</strong>.',
'The fixed policy grasps, reorients and moves the real brush.',
'The goal interface specifies tool motion rather than robot finger trajectories.']),`The project video places the human demonstration and extracted goal poses alongside real robot execution. Use it to connect the two branches of the pipeline. The robot policy does not update its weights on this new trajectory. Goal progression is event-driven, as described on the preceding slide. Treat the rendered goal display as an explanatory visualization, not additional evidence from a digital-twin experiment.`,`Official project video · inference.mp4 · Paper §III-C`);
add('03 / Method','What “zero-shot” means in this paper',table(['Absent at deployment','Still required at deployment'],[
['Policy training on the target tool','A metric-scale mesh for pose tracking'],
['Policy training on the target task','An RGB-D human demonstration'],
['Task-specific reward tuning','A grasp region and canonical frame'],
['Real-world policy fine-tuning','Online object tracking and calibrated robot sensing']])+f(call('Zero-shot refers to policy transfer across target objects and trajectories.'),1),`This slide prevents the most likely misunderstanding. Zero-shot does not mean no human input, no object modeling anywhere, or autonomous discovery of what task to do. It means the manipulation policy does not undergo target-object or target-trajectory training. The human video and perception setup provide information at deployment. This also explains why the system is compatible with, rather than necessarily opposed to, high-level foundation models.`,`Paper §III-C · Human Video Processing appendix`);
add('04 / Evidence','DexToolBench evaluates trajectory progress',`<div class="statrow"><div><strong>6</strong><span>tool categories</span></div><div><strong>12</strong><span>object instances</span></div><div><strong>24</strong><span>object–task variations</span></div><div><strong>120</strong><span>real-world rollouts</span></div></div>`+eq(String.raw`\mathrm{Task\ Progress}=\frac{\text{goal poses reached}}{\text{goal poses in the sequence}}\times100\%`,true)+f(call('The 2 cm tolerance is a maximum keypoint-distance criterion, jointly reflecting translation and rotation.'),1)+f(call('A completed trajectory does not necessarily imply successful physical task completion.',true),2),`There are five rollouts per object-task variation. The hardware is a 7-DoF KUKA iiwa arm with a 22-DoF Sharpa hand. The paper counts the fraction of sequential goal poses reached, with a two-centimeter keypoint distance threshold at evaluation. This is not a two-centimeter translation-only rule. In particular, screwdriver trials measure free-space spinning, not successful screw insertion or tightening.`,`Paper §IV · DexToolBench appendix · Task Progress definition`);
const overall=V.mean(V.results.flatMap(r=>r[3]));
add('04 / Evidence','Transfer is strong but uneven across tools',V.performance()+small(`Presenter aggregation of Table II: <b>${overall.toFixed(1)}% mean Task Progress</b> across 120 rollouts. Each category has 20 rollouts.`),`This chart is recomputed from the per-rollout entries in Table II rather than estimated from raster bars. Equal numbers of trials per category make the overall rollout mean and category mean equivalent here. Erasers need less in-hand reorientation and achieve full trajectory progress. Screwdrivers require both reorientation and continuous spinning and are the hardest category. These averages are not binary task success rates, and this chart does not add uncertainty estimates that the paper has not provided.`,`Real robot · Presenter aggregation of paper Table II · Units: Task Progress (%)`);
add('04 / Evidence','In-hand control matters in the brush comparison',V.baseline()+small('Five rollouts per variation. Same red-brush task, two initial orientations. Values from Fig. 5.'),`The comparison isolates different limitations. Kinematic retargeting does not reliably establish the required contacts. A fixed grasp can work when no tool rotation is needed, but the harder starting orientation makes the required arm motion problematic. SimToolReal can rotate the tool within the hand. On the easier variation the difference from fixed grasp is 98.0 minus 61.0, or 37 percentage points. Do not call this a 37 percent relative improvement or an average across all benchmark tasks. The fixed-grasp baseline initially uses SimToolReal to acquire the object.`,`Real robot · Paper Fig. 5 · Task Progress (%) · Limited to two brush variations`);
add('04 / Evidence','Specialists are sensitive to changed tools and goals',cols(fig(6,'Paper Fig. 6 · Comparison to specialist RL policies',378),list(['Match specialist performance on its training setup.','Keep high progress when either the tool or the trajectory changes.','All three conditions are evaluated in simulation.'])),`The specialists use the same policy architecture and reward setup, but train on one object and one trajectory per category. Six specialists are evaluated over ten rollouts each per condition. The general policy performs comparably on their training configurations and is much more robust to changed object instances or task trajectories. This is simulation evidence and should not be described as a real-world comparison against specialists. The figure supports qualitative magnitude comparisons; no invented exact bar heights are reported.`,`Simulation · Paper Fig. 6 · §IV-C`);
add('04 / Evidence','The proxy objective predicts downstream progress',cols(fig(7,'Paper Fig. 7 · Training reward and unseen-task evaluation',375),`<h3>Evidence for the abstraction</h3>${p('Random-pose training improves alongside unseen tool-trajectory performance.')}${f(call('Support for the proxy objective, with no guarantee of functional task success.'),1)}`),`The left curve measures training reward on randomized primitive objects. The right measures zero-shot Task Progress on DexToolBench objects in simulation at checkpoints. They trend upward together, although the right curve is not strictly monotonic. The plot reaches 120 billion environment steps, so avoiding real demonstrations does not make this computation-free. This is correlational evidence for the usefulness of the training objective, not a theorem or an in-the-wild scaling law.`,`Simulation · Paper Fig. 7 · §IV-D · Horizontal axis: billions of environment steps`);
add('04 / Evidence','Perception is the largest recorded failure category',V.failures()+f(call('A robust controller cannot compensate for a tracker that loses the object entirely.'),1),`These percentages are shares of failures, not shares of all 120 trials. Pose tracking struggles with heavy hand occlusion, rotational symmetry and low contrast. The paper describes a long screwdriver with colored tape to reduce rotational symmetry. Heavy objects are more likely to drop, and thin geometry makes in-hand reorientation harder. This decomposition motivates improving state estimation, but it does not show that a VLM alone can supply accurate high-rate pose tracking.`,`Real robot · Paper §IV-A · Real-World Experiment Additional Analysis appendix`);
add('04 / Evidence','Recovery depends on retaining usable state feedback',videoSlide('recovery','SimToolReal project: recovery behavior',[
'The policy can attempt to regrasp after a manipulation error.',
'Recovery requires the object to remain reachable and trackable.',
'This is a qualitative behavior, not an evaluated universal recovery guarantee.']),`Play the recovery excerpt as a concrete example of why closed-loop policies matter. The authors report regrasp attempts despite training resets after drops. Keep the claim conditional: the object must remain in the workspace and the visual tracker must still provide usable state. The clip does not establish reliability under arbitrary disturbances or unseen clutter.`,`Official project video · failureRecovery.m4v · Paper §IV-A`);
add('04 / Evidence','The pose interface leaves important state out',table(['Assumption or omission','Where it can fail'],[
['Rigid tool state','Scissors and articulated tools need internal joint state.'],
['Environment-blind policy inputs','Clutter can make a pose path collide with the scene.'],
['No explicit task-force objective','Correct tool motion may not deliver the required force.'],
['Fixed high-level goal sequence','The system does not replan the task when the world changes.']])+f(call('The demonstrated result is reusable trajectory execution under a structured deployment pipeline.'),1),`The limitations follow from the strength of the abstraction. By discarding much of the scene and task, the controller becomes reusable, but it also loses information needed for collision avoidance, contact outcomes and dynamic replanning. The authors explicitly acknowledge rigid-tool, environment-blind, high-force and fixed-goal limitations. These are the correct starting point for the proposed research extensions.`,`Paper §V · Author-acknowledged limitations`);
add('05 / Discussion','A complementary route beyond end-to-end action models',`<div class="scope-label">Hypothesis 1 · Presenter discussion</div>`+cols(`<h3>What this work establishes</h3>${p('A reusable motor policy can emerge from structured simulation and transfer to new tools without policy fine-tuning.')}`,`<h3>What remains open</h3>${p('Autonomous task discovery, scene understanding and reliable adaptation in unstructured environments.')}`)+f(call('A plausible route toward in-the-wild deployment: structured RL skills composed by a high-level system.'),1)+f(small('This paper neither demonstrates online in-the-wild skill learning nor eliminates foundation models.'),2),`Refine the original hypothesis by separating acquiring a controller in simulation from learning new skills online in the world. SimToolReal establishes transfer of a pretrained controller within its tested setup. It already relies on vision foundation models. The useful contrast is therefore with scaling end-to-end action learning as the only route to motor competence, not with large models in every part of the system. A semantic planner and a reusable RL controller may be complementary.`,`Presenter hypothesis · Grounded in §III–V · Not an experimental conclusion`);
add('05 / Discussion','Other interactions may admit compact task interfaces',`<div class="scope-label">Hypothesis 2 · Presenter discussion</div>`+table(['Interaction family','Candidate task interface','Extra state likely needed'],[
['Rigid object transport / reorientation','Object poses in SE(3)','Obstacle and contact geometry'],
['Doors, drawers and other mechanisms','Articulation state or constrained pose path','Joint constraints and contact mode'],
['Insertion or forceful surface work','Pose plus contact / wrench targets','Force, compliance and environment state'],
['Deformable-object manipulation','Shape or task-relevant keypoints','Deformation and contact history']])+f(call('The research question is which compact state is sufficient for each interaction family.'),1),`The strongest extension is not that everything reduces to six-dimensional pose. It is that many tasks may admit a compact, reusable goal interface paired with a learned controller. Whether that interface is sufficient depends on the interaction. Opening a mechanism requires articulation constraints, insertion often needs force and compliance, and deformable manipulation needs shape state. These examples are proposed research directions rather than tasks validated by the paper.`,`Presenter hypotheses · Beyond the paper's rigid-tool setting`);
add('05 / Discussion','A lightweight VLM could improve the semantic interface',`<div class="scope-label">Hypothesis 3 · Proposed architecture</div>`+V.hybrid()+f(call('A semantic model may reduce prompting and improve goal selection. Metric, low-latency tracking still needs validation.'),2),`The original idea is promising if the module boundary is precise. A lightweight VLM might select the tool and graspable region, interpret a demonstration, or propose and revise subgoals. That is different from continuously estimating metric six-degree-of-freedom pose at the accuracy and rate required by the controller. A hybrid with geometry-grounded tracking and confidence monitoring is a more defensible first experiment. No result in this paper compares VLMs or proves such a replacement improves generalization.`,`Presenter proposal · Motivated by the semi-automated perception pipeline and failure analysis`);
add('05 / Discussion','Three experiments would test these extensions',table(['Proposed change','Controlled comparison','Measure beyond Task Progress'],[
['VLM-assisted semantic setup','Manual point prompts vs. VLM region proposals','Human intervention count, grasp-region accuracy'],
['Better closed-loop state estimation','Original tracker vs. multi-view / grounded hybrid','Pose error, latency, tracking-loss rate'],
['Richer task interface','Pose-only vs. pose + contact / force + replanning','Functional completion, contact safety, transfer']])+f(call('Keep the motor policy fixed first to separate perception gains from controller changes.'),1),`These are suggested experiments, not an implementation claim. Change one part of the pipeline at a time and measure both interface quality and end-to-end outcomes. A VLM may reduce setup effort while worsening precision, so intervention counts alone are insufficient. For pose-plus-contact interfaces, retraining may be necessary; comparisons should control the simulation budget and evaluation objects. Functional success should be task-specific, such as debris removed or insertion completed, rather than inferred from pose progress.`,`Presenter experimental agenda · Not evaluated in SimToolReal`);
add('06 / Takeaways','A reusable motor skill needs a well-chosen task interface',steps([
['Specify motion at the object level','Human video supplies goals without prescribing robot finger motion.'],
['Learn the controller over varied physics','Procedural primitives and random goals support policy reuse.'],
['Preserve the boundary of the evidence','Strong trajectory transfer still leaves perception, force and replanning open.']])+f(`<p class="quote">Which parts of a manipulation task can we safely compress into a reusable goal interface?</p>`,1),`Close by returning to the initial question about how robots can acquire tool-use skills. This paper demonstrates an effective division of labor: human object-motion specification, geometric perception and a simulation-trained motor controller. The most general lesson is about interface design, not a claim that all robotics problems reduce to pose tracking. Invite discussion on how to identify sufficient state and objectives for broader interactions.`,`Paper contributions and presenter synthesis`);
add('Backup','Pose error couples translation and rotation',cols(fig(9,'Paper Fig. 9 · Four object-frame pose keypoints',300),eq(String.raw`d(o_t,g)=\max_{i=1,\ldots,4}\|o_{t,i}-g_i\|`,true)+list(['Reward keypoints use fixed scales across objects.','Observation keypoints depend on the object instance.','Training tolerance: 1 cm. Evaluation: 2 cm.']))+call('A “2 cm pose error” is a keypoint-space criterion, not a separate orientation threshold.'),`The reward uses fixed scales of 14 by 3 by 3 centimeters to define four local keypoints. This makes pitch and yaw matter more than roll around the long tool axis. The observation representation instead uses instance-specific dimensions. Distinguishing the two prevents an incorrect interpretation of the evaluation tolerance as only translation accuracy or a uniform angular tolerance for every rotation axis.`,`Paper Reward Function Details appendix · Table I · §IV`);
add('Backup','Ablations identify important RL ingredients',cols(fig(8,'Paper Fig. 8 · Training reward, mean over five seeds',376),list(['Replacing SAPG with PPO lowers training reward.','Removing the asymmetric critic severely hinders learning.','These curves cover 9B environment steps.']))+small('This ablation measures training reward, not real-world functional task completion.'),`The full policy uses SAPG and an asymmetric critic. Both tested removals produce substantially lower reward under matched settings. The figure does not isolate all choices: there is no complete ablation here for procedural diversity, LSTM memory, every randomization term or the perception pipeline. The nine-billion-step ablation horizon also differs from the 120-billion-step checkpoint study.`,`Simulation · Paper Fig. 8 · §IV-E`);
add('Backup','Implementation details that matter for reproduction',table(['Component','Reported configuration'],[
['Robot','7-DoF KUKA iiwa 14 + 22-DoF Sharpa left hand'],
['Simulator / parallelism','IsaacGym / 24,576 environments'],
['Simulation / control','120 Hz / 60 Hz'],
['Actor','LSTM[1024] + MLP[1024, 1024, 512, 512]'],
['Critic','MLP[1024, 1024, 512, 512], privileged simulator state'],
['Pose observations','1 cm translation noise, 5° rotation noise, up to 10-step delay'],
['Perturbations','5 N force scale, 0.5 Nm torque scale']
],true),`The actor is not a small policy in the sense of having only a tiny MLP. It includes a 1024-unit recurrent layer and several large hidden layers. The paper reports simulator parallelism and environment-step counts, but this deck does not infer wall-clock time or GPU cost from them. Reproducing transfer also requires the matched robot gains, delays, safety ranges and perception calibration described in the appendix.`,`Paper Table I · Simulation Training Details and Sim-to-Real Details appendices`);
for(const [start,end,label] of [[0,12,'Hammer, marker and eraser'],[12,24,'Brush, spatula and screwdriver']])add('Backup',`Real-world task breakdown: ${label}`,table(['Tool / instance','Trajectory','Mean progress'],V.results.slice(start,end).map(r=>[`${r[0]} / ${r[1]}`,r[2],V.mean(r[3]).toFixed(1)+'%']),true),`Each row averages five trials from Table II. Use the accompanying CSV for the five individual values. The chart and table compute means from the rounded per-rollout entries published in the paper, so an occasional last-decimal difference from a paper average is possible. These are fractions of pose goals reached, not fractions of trials that completed the physical task.`,`Real robot · Recomputed from Table II · Five rollouts per row`);
add('Backup','References, videos and source material',`<div class="references"><p><b>Main paper</b><br>Kedia, Lum, Bohg and Liu. <i>SimToolReal: An Object-Centric Policy for Zero-Shot Dexterous Tool Manipulation.</i><br><a href="https://arxiv.org/abs/2602.16863v2">arxiv.org/abs/2602.16863v2</a> · <a href="https://www.roboticsproceedings.org/rss22/p151.html">RSS 2026 proceedings</a></p><p><b>Project and code</b><br><a href="https://simtoolreal.github.io/">simtoolreal.github.io</a> · <a href="https://github.com/tylerlum/simtoolreal">github.com/tylerlum/simtoolreal</a></p><p><b>Closely related work</b><br>Chen et al. <i>Object-Centric Dexterous Manipulation from Human Motion Data.</i> CoRL 2024.<br>Lum et al. <i>Crossing the Human-Robot Embodiment Gap with Sim-to-Real RL Using One Human Demonstration.</i> 2025.<br>Petrenko et al. <i>DexPBT.</i> 2023.</p><p><b>Design reference</b><br><a href="https://github.com/Mizoreww/steerable-vla-talk">Mizoreww/steerable-vla-talk</a> and the previous A2A seminar deck.</p></div>`,`Paper figures and project videos retain their original authorship. Custom diagrams are explanatory schematics. Real-world aggregate charts derive from the published Table II data, provided in CSV form alongside this deck. The discussion section explicitly labels untested extensions. The package also contains English speaker notes and a detailed Chinese narrative assessment.`,`Sources and attribution`);

const css=await fs.readFile(out+'/src/style.css','utf8'),nav=await fs.readFile(out+'/src/navigation.js','utf8');
const html=slides.map((s,i)=>`<section class="slide ${s.cls} ${i===0?'active':''}" data-no="${i+1}">${s.cls==='cover'?s.body:`<header class="head"><div class="section-label">${s.section}</div><h2>${s.title}</h2><div class="rule"></div></header><div class="body">${s.body}</div>`}<div class="brand">SIMTOOLREAL</div><div class="pageno">${String(i+1).padStart(2,'0')} / ${slides.length}</div><div class="build-count"></div><footer class="cite">${s.source}</footer><aside class="notes-hidden">${s.note}</aside></section>`).join('\n');
await fs.writeFile(out+'/slides.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SimToolReal · Research Seminar</title><link rel="stylesheet" href="assets/katex/katex.min.css"><style>${css}</style></head><body><main id="canvas">${html}</main><div id="lightbox"><img id="lightbox-img" alt="Enlarged paper figure"><div class="hint">Click or press Escape to close</div></div><nav id="hud"><button id="prev">◀</button><span><span id="cur"></span> / <span id="tot"></span></span><button id="next">▶</button><button id="all">Reveal · A</button><button id="full">Fullscreen · F</button><a href="index.html" target="_blank">Notes</a></nav><div id="progress"></div><script>${nav}</script></body></html>`);
await fs.writeFile(out+'/speaker_notes.md','# SimToolReal · English Speaker Notes\n\nSuggested duration: 35–40 minutes plus discussion. Slides 1–33 are the main talk. Slides 34–39 are backup. Use Right / Space for step reveals, A to reveal a whole page, F for fullscreen, and V for video play/pause. Clips are silent and run at original speed.\n\n'+slides.map((s,i)=>`## ${i+1}. ${s.title}\n\n${s.note}\n\nSource: ${s.source}`).join('\n\n'));
await fs.writeFile(out+'/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SimToolReal · Presenter Notes</title><style>body{background:#edf2ef;margin:0;font:18px/1.7 Arial,sans-serif;color:#283531}main{max-width:1000px;margin:auto;background:white;padding:55px}h1{font:54px Georgia,serif;color:#1d7d76}h2{font:28px Georgia,serif}a{color:#1d7d76}section{border-top:1px solid #d6e5e1;padding:25px 0}.source{font-size:13px;color:#71847e}ol{columns:2;font-size:15px}@media(max-width:700px){main{padding:25px}ol{columns:1}}</style><main><h1>SimToolReal</h1><p>English speaker notes · 35–40 minute seminar</p><p><a href="slides.html">Open presentation</a> · <a href="SimToolReal_slides.pdf">PDF</a> · <a href="paper/narrative_assessment_zh.md">Narrative assessment (Chinese)</a></p><p>Right / Space: next build. Left: previous build. A: reveal all. F: fullscreen. V: play/pause video. Click figures to enlarge. All videos are local and silent. PDF shows the complete builds and video stills.</p><ol>${slides.map((s,i)=>`<li><a href="#s${i+1}">${s.title}</a></li>`).join('')}</ol>${slides.map((s,i)=>`<section id="s${i+1}"><div class="source">SLIDE ${i+1} · ${s.section}</div><h2><a href="slides.html#${i+1}">${s.title}</a></h2><p>${s.note}</p><div class="source">${s.source}</div></section>`).join('')}</main></html>`);
await fs.writeFile(out+'/src/deck-data.json',JSON.stringify(slides,null,2));
await fs.writeFile(out+'/paper/real_world_results.csv','category,instance,trajectory,r1,r2,r3,r4,r5,mean_progress\n'+V.results.map(r=>[...r.slice(0,3),...r[3],V.mean(r[3]).toFixed(2)].join(',')).join('\n')+'\n');
console.log('Built',slides.length,'slides. Overall Task Progress:',overall.toFixed(3));
