import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import katex from 'katex';
import * as V from './visuals.mjs';
const out=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const p=s=>`<p class="lead">${s}</p>`,small=s=>`<p class="small">${s}</p>`;
const f=(s,n=1)=>`<div class="fragment" data-step="${n}">${s}</div>`;
const call=(s,w=false)=>`<div class="callout${w?' warm':''}">${s}</div>`;
const cols=(a,b,wide=false)=>`<div class="cols${wide?' wide':''}"><div>${a}</div><div>${b}</div></div>`;
const list=a=>`<ul class="bul">${a.map(s=>`<li>${s}</li>`).join('')}</ul>`;
const eq=(s,sm=false)=>`<div class="equation${sm?' sm':''}">${katex.renderToString(s,{displayMode:true,throwOnError:true})}</div>`;
const fig=(n,c,h=370)=>`<figure class="paperfig"><img src="assets/fig${String(n).padStart(2,'0')}.png" alt="${c}" style="max-height:${h}px"><figcaption>${c}</figcaption></figure>`;
const table=(heads,rows,compact=false)=>`<table class="tb${compact?' compact':''}"><thead><tr>${heads.map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr class="${String(r[0]).startsWith('SimToolReal')?'highlight':''}">${r.map(x=>`<td><span>${x}</span></td>`).join('')}</tr>`).join('')}</tbody></table>`;
const video=(n,c)=>`<div class="video-wrap"><video controls muted playsinline preload="none" poster="assets/videos/${n}.jpg" aria-label="${c}"><source src="assets/videos/${n}.mp4" type="video/mp4"></video><img class="video-poster" src="assets/videos/${n}.jpg" alt="Video still: ${c}"><div class="video-caption"><span>${c} · 1× speed · silent excerpt</span><a href="https://simtoolreal.github.io/">Original project video ↗</a></div></div>`;
const videoSlide=(name,c,cues)=>cols(video(name,c),`<div class="stack"><div class="eyebrow">What to watch</div>${cues.map(s=>`<p class="video-cue">${s}</p>`).join('')}</div><button class="play-video">Play / pause · V</button>`,true);
const steps=a=>`<div class="number-list">${a.map((r,i)=>`<span class="num">0${i+1}</span><div><h3>${r[0]}</h3><p>${r[1]}</p></div>`).join('')}</div>`;
const slides=[];
const add=(section,title,body,note,source='Kedia et al. · SimToolReal · arXiv:2602.16863v2',cls='')=>slides.push({section,title,body,note,source,cls});
add('','SimToolReal',`<div class="cover-bar"></div><div class="cover-copy"><div class="eyebrow">Research seminar</div><h1>SimTool<span class="teal">Real</span></h1><div class="subtitle">An Object-Centric Policy for<br>Zero-Shot Dexterous Tool Manipulation</div><p class="cover-question">Can one reusable controller<br>turn tool motion into robot skill?</p><div class="authors">Kushal Kedia* · Tyler Ga Wei Lum*<br>Jeannette Bohg · C. Karen Liu<br><span class="muted">Cornell University · Stanford University</span></div><div class="venue">RSS 2026 · Based on arXiv v2, 24 February 2026</div></div><img class="cover-art" src="assets/fig13.png" alt="Real tools and their reconstructed meshes">`,`The central question is how to reuse a dexterous controller across unfamiliar tools and goal trajectories. SimToolReal trains such a controller on simple synthetic tools in simulation. At deployment, human demonstrations provide object motion goals, while the robot decides how its own hand and arm should realize them. We will discuss why dexterous tool use is difficult, question what demonstrations should provide, and then explain the object-centric controller and its evidence. The paper is listed in the RSS 2026 proceedings.`,undefined,'cover');

add('01 / Motivation','Why is robot tool manipulation difficult?',videoSlide('difficulty','SimToolReal project: why tool manipulation is hard',[
'<strong>Acquire:</strong> grasp a thin tool on a flat surface.',
'<strong>Reorient:</strong> move it within the fingers.',
'<strong>Interact:</strong> resist external forces without losing the tool.']),`This short author video motivates why tool manipulation is more than moving the end effector. Thin objects constrain initial finger placement. Large orientation changes can exceed the arm workspace under a fixed grasp. Tool-environment contact adds forces and torques. Multi-fingered hands offer contact choices but make teleoperation and learning harder. These difficulties motivate the comparisons on the next pages.`,`Paper §I · Official project video ToolManipHard.mp4`);

add('01 / Motivation','Why not simply imitate a demonstration?',p('Brainstorm: what would a useful demonstration have to teach?')+cols(
f('<h3>Teleoperate this robot</h3>'+list(['Robot actions provide direct supervision.','Dexterous contacts are hard to demonstrate with limited force feedback.']),1),
f('<h3>Retarget a human video</h3>'+list(['Human tool use is easy to demonstrate.','Different fingers and contacts make direct motion transfer unreliable.']),2)
)+f(call('Could we demonstrate the desired tool motion and let the robot learn its own contact strategy?'),3),
`Pause on the opening question and invite imitation learning, retargeting, planning or RL as possible routes. Reveal the two demonstration routes in turn. The concern is the cost and suitability of action supervision for this dexterous setting. Diffusion or VLA policies can be trained through imitation, but changing the policy architecture does not itself supply high-quality contact data. This is motivation, not evidence that IL cannot work. The paper has no strong learned IL/VLA baseline. The final question leads directly to the paper's proposed interface.`,
'Paper §I–II · Brainstorm framing · No direct learned IL/VLA comparison');

add('02 / Core idea','The transferable interface is the tool motion',V.reduction()+f(call('Object goals specify the motion. RL discovers robot-specific grasps and in-hand actions.'),3),`This is the conceptual pivot. The human provides a sequence of rigid-tool configurations. A goal-conditioned controller learns how to move the tool between configurations using this robot's arm and hand. It is related to functional or object-centric retargeting, but the controller is trained in advance on randomized primitives rather than trained for each demonstration. The arrow from goals to policy denotes conditioning, not policy fine-tuning.`,`Paper §III-A · Presenter schematic`);

add('02 / System','A reusable controller inside a three-stage system',V.architecture(),
`Start with the shaded training lane. Procedural tools and random goals train one reusable actor in simulation. Reveal task setup next: a human RGB-D demonstration and semi-automated perception produce a mesh, a grasp box and goal poses. Reveal online execution last. The mesh supports pose tracking, while robot proprioception and the current tool pose close the loop around the frozen actor. The dashed connection denotes transferring policy weights, not fine-tuning. At deployment, the actor receives the current goal and grasp box in addition to live state. This simplified architecture combines the paper's training and deployment diagrams. Low-level perception details are intentionally expanded in the next pages rather than inside this overview.`,
'Paper §III-B–C · Simplified redraw of Figs. 2–3', 'architecture-slide');

add('02 / System','The actor converts object goals into robot actions',V.controller()+f(call('The LSTM retains interaction history while the current goal specifies what to reach.'),2),
`Explain each input before revealing the output. Proprioception describes the robot. The tracked tool pose and target pose describe the goal-reaching problem. A coarse box identifies the graspable region. LSTM history helps under partial observation, including unknown physical properties. The MLP produces actions that become 29 arm and hand joint-position targets. The actor does not consume RGB directly, detailed meshes or explicit mass and inertia estimates. The asymmetric critic uses privileged state only during training. Exact layer sizes are in backup.`,
'Paper §III-A–B · Table I · Simplified actor diagram');

add('02 / Method','Training varies objects and goals together',V.training()+f(call('Handle–head geometry provides the prior. Grasp shaping and pose-reaching rewards teach the control.'),3),`Tools vary in handle/head dimensions and density. The full reward includes smoothness, grasp shaping and progress toward pose goals. SAPG, an asymmetric critic and domain randomization support learning and transfer. At reset the environment samples an object and robot initialization. The first goal can require a large motion or reorientation. Subsequent goals are near the preceding one, encouraging trajectory-like transitions. Unlike test-time demonstrations, these training goals are randomly generated. Procedural object diversity broadens the contact and inertial situations the policy encounters. IsaacGym provides 24,576 parallel environments in the reported configuration.`,`Paper §III-B · Table I · Presenter schematic`);

add('02 / Method','Perception supplies state, goals advance on success',V.loop()+f(small('Setup: prompted SAM 2 + SAM 3D recover geometry. FoundationPose estimates the tool poses.'),3),`The setup is semi-automated: user point prompts identify the tool and handle/head, SAM 3D uses captured depth for metric scale, and FoundationPose extracts the demonstrated trajectory and tracks the live tool. Separate the three rates explicitly. Human trajectory processing downsamples a 30 Hz video trajectory to 3 Hz waypoints and trims its stationary pre-grasp portion. The live pose tracker updates at 30 Hz. Robot control runs at 60 Hz. The active goal changes only after the pose error falls below the threshold, not every one-third of a second. The robot may therefore take longer to execute a difficult transition than the person did. Zero-shot means no target-tool or target-trajectory policy training. A demonstration, geometry setup and live sensing are still required.`,`Paper §III-C · Table I · Goal Pose Sequence appendix · Presenter schematic`);

add('02 / Method','The closed loop follows unseen tool trajectories',videoSlide('inference','SimToolReal project: real-world inference',[
'The human demonstration supplies the <strong>tool-motion goals</strong>.',
'The fixed policy grasps, reorients and moves the real brush.',
'The goal interface specifies tool motion rather than robot finger trajectories.']),`The project video places the human demonstration and extracted goal poses alongside real robot execution. Use it to connect the two branches of the pipeline. The robot policy does not update its weights on this new trajectory. Goal progression is event-driven, as described on the preceding slide. Treat the rendered goal display as an explanatory visualization, not additional evidence from a digital-twin experiment.`,`Official project video · inference.mp4 · Paper §III-C`);

add('03 / Evidence','Real-world transfer across six tool categories',small('<b>12 objects · 24 object–task variations · 120 rollouts</b><br>Task Progress = fraction of sequential pose goals reached.')+V.performance()+small(`Mean progress: <b>${V.mean(V.results.flatMap(r=>r[3])).toFixed(1)}%</b>. This metric does not establish functional task success.`),
`DexToolBench evaluates six categories with two instances and two trajectories each, using five rollouts per variation. This chart recomputes category means from all 120 published rollout values. The evaluation threshold is 2 cm maximum pose-keypoint error, combining translation and rotation. Erasers need less in-hand rotation, while screwdrivers require reorientation and spinning. The overall mean is 79.3% trajectory progress, not 79.3% completed tasks. Screwdriver trials involve free-space spinning rather than screw insertion or tightening. Source rounding may affect the last decimal.`,
'Real robot · Presenter aggregation of Table II · 20 trials per category','results-slide');

add('03 / Evidence','In-hand control matters in the brush comparison',V.baseline()+small('Five rollouts per variation. Same red-brush task, two initial orientations. Values from Fig. 5.'),`The comparison isolates different limitations. Kinematic retargeting does not reliably establish the required contacts. A fixed grasp can work when no tool rotation is needed, but the harder starting orientation makes the required arm motion problematic. SimToolReal can rotate the tool within the hand. On the easier variation the difference from fixed grasp is 98.0 minus 61.0, or 37 percentage points. Do not call this a 37 percent relative improvement or an average across all benchmark tasks. The fixed-grasp baseline initially uses SimToolReal to acquire the object.`,`Real robot · Paper Fig. 5 · Task Progress (%) · Limited to two brush variations`);

add('03 / Evidence','Specialists are sensitive to changed tools and goals',cols(fig(6,'Paper Fig. 6 · Comparison to specialist RL policies',378),list(['Match specialist performance on its training setup.','Keep high progress when either the tool or the trajectory changes.','All three conditions are evaluated in simulation.'])),`The specialists use the same policy architecture and reward setup, but train on one object and one trajectory per category. Six specialists are evaluated over ten rollouts each per condition. The general policy performs comparably on their training configurations and is much more robust to changed object instances or task trajectories. This is simulation evidence and should not be described as a real-world comparison against specialists. The figure supports qualitative magnitude comparisons; no invented exact bar heights are reported.`,`Simulation · Paper Fig. 6 · §IV-C`);

add('03 / Evidence','Perception is the largest recorded failure category',V.failures()+f(call('A robust controller cannot compensate for a tracker that loses the object entirely.'),1),`These percentages are shares of failures, not shares of all 120 trials. Pose tracking struggles with heavy hand occlusion, rotational symmetry and low contrast. The paper describes a long screwdriver with colored tape to reduce rotational symmetry. Heavy objects are more likely to drop, and thin geometry makes in-hand reorientation harder. This decomposition motivates improving state estimation, but it does not show that a VLM alone can supply accurate high-rate pose tracking.`,`Real robot · Paper §IV-A · Real-World Experiment Additional Analysis appendix`);

add('03 / Evidence','The pose interface leaves important state out',table(['Assumption or omission','Where it can fail'],[
['Rigid tool state','Scissors and articulated tools need internal joint state.'],
['Environment-blind policy inputs','Clutter can make a pose path collide with the scene.'],
['No explicit task-force objective','Correct tool motion may not deliver the required force.'],
['Fixed high-level goal sequence','The system does not replan the task when the world changes.']])+f(call('The demonstrated result is reusable trajectory execution under a structured deployment pipeline.'),1),`The limitations follow from the strength of the abstraction. By discarding much of the scene and task, the controller becomes reusable, but it also loses information needed for collision avoidance, contact outcomes and dynamic replanning. The authors explicitly acknowledge rigid-tool, environment-blind, high-force and fixed-goal limitations. These are the correct starting point for the proposed research extensions.`,`Paper §V · Author-acknowledged limitations`);

add('04 / Discussion','How far can a compact task interface take us?', '<div class="scope-label">Presenter hypotheses · Beyond the paper’s experiments</div>'+cols(
'<h3>A complementary route to general skills</h3>'+p('Structured simulation can train reusable motor skills that a higher-level system composes.')+f(small('The paper shows transfer in a structured setup. Online skill learning in the wild remains open.'),1),
'<h3>Other interactions, other state</h3>'+p('Rigid motion may use pose goals. Insertion may need force and contact. Doors may need articulation state.')+f(small('The question is which compact interface retains enough information for the task.'),2)
)+f(call('The generalizable idea is task-interface design. Its sufficient state depends on the interaction.'),3),
`This page consolidates the first two research hypotheses. First, reusable RL motor skills could complement end-to-end action models, but the work does not demonstrate autonomous online learning in the wild. Its perception already uses vision foundation models. Second, object-centric pose goals may inspire compact interfaces for other interactions, but six-dimensional rigid pose alone will be insufficient for articulated, deformable or force-sensitive tasks. Both statements are extensions to test, not conclusions established by SimToolReal.`,
'Presenter discussion · Motivated by paper §III–V');

add('04 / Discussion','A lightweight VLM could improve the semantic interface',`<div class="scope-label">Hypothesis 3 · Proposed architecture</div>`+V.hybrid()+f(call('A semantic model may reduce prompting and improve goal selection. Metric, low-latency tracking still needs validation.'),2),`A clean first experiment would compare manual point prompts with VLM-proposed regions while holding the motor policy fixed, measuring intervention count, pose accuracy, latency and task completion. The original idea is promising if the module boundary is precise. A lightweight VLM might select the tool and graspable region, interpret a demonstration, or propose and revise subgoals. That is different from continuously estimating metric six-degree-of-freedom pose at the accuracy and rate required by the controller. A hybrid with geometry-grounded tracking and confidence monitoring is a more defensible first experiment. No result in this paper compares VLMs or proves such a replacement improves generalization.`,`Presenter proposal · Motivated by the semi-automated perception pipeline and failure analysis`);

add('05 / Takeaways','A reusable motor skill needs a well-chosen task interface',steps([
['Specify motion at the object level','Human video supplies goals without prescribing robot finger motion.'],
['Learn the controller over varied physics','Procedural primitives and random goals support policy reuse.'],
['Preserve the boundary of the evidence','Strong trajectory transfer still leaves perception, force and replanning open.']])+f(`<p class="quote">Which parts of a manipulation task can we safely compress into a reusable goal interface?</p>`,1),`Close by returning to the initial question about how robots can acquire tool-use skills. This paper demonstrates an effective division of labor: human object-motion specification, geometric perception and a simulation-trained motor controller. The most general lesson is about interface design, not a claim that all robotics problems reduce to pose tracking. Invite discussion on how to identify sufficient state and objectives for broader interactions.`,`Paper contributions and presenter synthesis`);

add('Backup','Pose error couples translation and rotation',cols(fig(9,'Paper Fig. 9 · Four object-frame pose keypoints',300),eq(String.raw`d(o_t,g)=\max_{i=1,\ldots,4}\|o_{t,i}-g_i\|`,true)+list(['Reward keypoints use fixed scales across objects.','Observation keypoints depend on the object instance.','Training tolerance: 1 cm. Evaluation: 2 cm.']))+call('A “2 cm pose error” is a keypoint-space criterion, not a separate orientation threshold.'),`The reward uses fixed scales of 14 by 3 by 3 centimeters to define four local keypoints. This makes pitch and yaw matter more than roll around the long tool axis. The observation representation instead uses instance-specific dimensions. Distinguishing the two prevents an incorrect interpretation of the evaluation tolerance as only translation accuracy or a uniform angular tolerance for every rotation axis.`,`Paper Reward Function Details appendix · Table I · §IV`);

add('Backup','Ablations identify important RL ingredients',cols(fig(8,'Paper Fig. 8 · Training reward, mean over five seeds',376),list(['Replacing SAPG with PPO lowers training reward.','Removing the asymmetric critic severely hinders learning.','These curves cover 9B environment steps.']))+small('This ablation measures training reward, not real-world functional task completion.'),`The full policy uses SAPG and an asymmetric critic. Both tested removals produce substantially lower reward under matched settings. The figure does not isolate all choices: there is no complete ablation here for procedural diversity, LSTM memory, every randomization term or the perception pipeline. The nine-billion-step ablation horizon also differs from the 120-billion-step checkpoint study.`,`Simulation · Paper Fig. 8 · §IV-E`);

add('Backup','Implementation details that matter for reproduction',table(['Component','Reported configuration'],[
['Robot','7-DoF KUKA iiwa 14 + 22-DoF Sharpa left hand'],
['Simulator / parallelism','IsaacGym / 24,576 environments'],
['Simulation / control','120 Hz / 60 Hz'],
['Actor','LSTM[1024] + MLP[1024, 1024, 512, 512]'],
['Critic','MLP[1024, 1024, 512, 512], privileged simulator state'],
['Pose observations','1 cm translation noise, 5° rotation noise, up to 10-step delay'],
['Perturbations','5 N force scale, 0.5 Nm torque scale']
],true),`The actor is not a small policy in the sense of having only a tiny MLP. It includes a 1024-unit recurrent layer and several large hidden layers. The paper reports simulator parallelism and environment-step counts, but this deck does not infer wall-clock time or GPU cost from them. Reproducing transfer also requires the matched robot gains, delays, safety ranges and perception calibration described in the appendix.`,`Paper Table I · Simulation Training Details and Sim-to-Real Details appendices`);

add('Backup','References, videos and source material',`<div class="references"><p><b>Main paper</b><br>Kedia, Lum, Bohg and Liu. <i>SimToolReal: An Object-Centric Policy for Zero-Shot Dexterous Tool Manipulation.</i><br><a href="https://arxiv.org/abs/2602.16863v2">arxiv.org/abs/2602.16863v2</a> · <a href="https://www.roboticsproceedings.org/rss22/p151.html">RSS 2026 proceedings</a></p><p><b>Project and code</b><br><a href="https://simtoolreal.github.io/">simtoolreal.github.io</a> · <a href="https://github.com/tylerlum/simtoolreal">github.com/tylerlum/simtoolreal</a></p><p><b>Closely related work</b><br>Chen et al. <i>Object-Centric Dexterous Manipulation from Human Motion Data.</i> CoRL 2024.<br>Lum et al. <i>Crossing the Human-Robot Embodiment Gap with Sim-to-Real RL Using One Human Demonstration.</i> 2025.<br>Petrenko et al. <i>DexPBT.</i> 2023.</p><p><b>Design reference</b><br><a href="https://github.com/Mizoreww/steerable-vla-talk">Mizoreww/steerable-vla-talk</a> and the previous A2A seminar deck.</p></div>`,`Paper figures and project videos retain their original authorship. Custom diagrams are explanatory schematics. Real-world aggregate charts derive from the published Table II data, provided in CSV form alongside this deck. The discussion section explicitly labels untested extensions. The package also contains English speaker notes and a detailed Chinese narrative assessment.`,`Sources and attribution`);

const css=await fs.readFile(out+'/src/style.css','utf8'),nav=await fs.readFile(out+'/src/navigation.js','utf8');
const html=slides.map((s,i)=>`<section class="slide ${s.cls} ${i===0?'active':''}" data-no="${i+1}">${s.cls==='cover'?s.body:`<header class="head"><div class="section-label">${s.section}</div><h2>${s.title}</h2><div class="rule"></div></header><div class="body">${s.body}</div>`}<div class="brand">SIMTOOLREAL</div><div class="pageno">${String(i+1).padStart(2,'0')} / ${slides.length}</div><div class="build-count"></div><footer class="cite">${s.source}</footer><aside class="notes-hidden">${s.note}</aside></section>`).join('\n');
await fs.writeFile(out+'/slides.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SimToolReal · Research Seminar</title><link rel="stylesheet" href="assets/katex/katex.min.css"><style>${css}</style></head><body><main id="canvas">${html}</main><div id="lightbox"><img id="lightbox-img" alt="Enlarged paper figure"><div class="hint">Click or press Escape to close</div></div><nav id="hud"><button id="prev">◀</button><span><span id="cur"></span> / <span id="tot"></span></span><button id="next">▶</button><button id="all">Reveal · A</button><button id="full">Fullscreen · F</button><a href="index.html" target="_blank">Notes</a></nav><div id="progress"></div><script>${nav}</script></body></html>`);
await fs.writeFile(out+'/speaker_notes.md','# SimToolReal · English Speaker Notes\n\nSuggested duration: 20–25 minutes plus discussion. Slides 1–17 are the main talk. Slides 18–21 are backup. Use Right / Space for step reveals, A to reveal a whole page, F for fullscreen, and V for video play/pause. Clips are silent and run at original speed.\n\n'+slides.map((s,i)=>`## ${i+1}. ${s.title}\n\n${s.note}\n\nSource: ${s.source}`).join('\n\n'));
await fs.writeFile(out+'/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SimToolReal · Presenter Notes</title><style>body{background:#edf2ef;margin:0;font:18px/1.7 Arial,sans-serif;color:#283531}main{max-width:1000px;margin:auto;background:white;padding:55px}h1{font:54px Georgia,serif;color:#1d7d76}h2{font:28px Georgia,serif}a{color:#1d7d76}section{border-top:1px solid #d6e5e1;padding:25px 0}.source{font-size:13px;color:#71847e}ol{columns:2;font-size:15px}@media(max-width:700px){main{padding:25px}ol{columns:1}}</style><main><h1>SimToolReal</h1><p>English speaker notes · 20–25 minute seminar</p><p><a href="slides.html">Open presentation</a> · <a href="SimToolReal_slides.pdf">PDF</a> · <a href="paper/narrative_assessment_zh.md">Narrative assessment (Chinese)</a></p><p>Right / Space: next build. Left: previous build. A: reveal all. F: fullscreen. V: play/pause video. Click figures to enlarge. All videos are local and silent. PDF shows the complete builds and video stills.</p><ol>${slides.map((s,i)=>`<li><a href="#s${i+1}">${s.title}</a></li>`).join('')}</ol>${slides.map((s,i)=>`<section id="s${i+1}"><div class="source">SLIDE ${i+1} · ${s.section}</div><h2><a href="slides.html#${i+1}">${s.title}</a></h2><p>${s.note}</p><div class="source">${s.source}</div></section>`).join('')}</main></html>`);
await fs.writeFile(out+'/src/deck-data.json',JSON.stringify(slides,null,2));
await fs.writeFile(out+'/paper/real_world_results.csv','category,instance,trajectory,r1,r2,r3,r4,r5,mean_progress\n'+V.results.map(r=>[...r.slice(0,3),...r[3],V.mean(r[3]).toFixed(2)].join(',')).join('\n')+'\n');
console.log('Built',slides.length,'slides. Overall Task Progress:',V.mean(V.results.flatMap(r=>r[3])).toFixed(3));

await fs.writeFile(out+'/assets/system_architecture.svg',V.architecture().replace('<defs>','<style>text{font-family:Arial,Helvetica,sans-serif}</style><defs>'));
